#!/usr/bin/env ansible-playbook
---

- name: Network config
  hosts: k8s_cluster
  become: true
  gather_facts: false
  pre_tasks:
    - name: Disable firewalld
      ansible.builtin.systemd:
        name: firewalld
        state: stopped
        enabled: false

    - name: Disable AD DNS
      ansible.builtin.lineinfile:
        path: /etc/resolv.conf
        regexp: 'nameserver 10.0.0.205'
        line: 'nameserver 10.0.0.205'
        state: absent

    - name: Set hostname
      ansible.builtin.hostname:
        name: "{{ inventory_hostname }}"
        use: systemd

- name: Proxy config
  hosts: k8s_cluster
  become: true
  gather_facts: false
  tags: [proxy]
  tasks:
    - name: Fix dnf
      ansible.builtin.lineinfile:
        path: /etc/dnf/dnf.conf
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        state: present
      loop:
        - regexp: '^proxy='
          line: "proxy={{ http_proxy | default('') }}"
        - regexp: '^repo_gpgcheck='
          line: 'repo_gpgcheck=0'
