#!/usr/bin/env ansible-playbook
---
# ~/.kube/config should be valid
- name: Manage KubeBlocks
  hosts: localhost
  become: false
  vars:
    # manage add-ons
    # Semaphore does not pass $HOME so path needs to be set explicitly.
    k8s_auth_kubeconfig: /home/semaphore/.kube/config
  tasks:
    - name: Install KubeBlocks
      ansible.builtin.include_role:
        name: bbaassssiiee.kubeblocks
      vars:
        use_kb_addons: true

    - name: Configure KubeBlocks
      ansible.builtin.include_role:
        name: clusterlust.kubeblocks
