#!/usr/bin/env ansible-playbook
---
# ~/.kube/config should be valid
- name: Manage Storage
  hosts: kube_node
  become: true
  gather_facts: true
  tasks:
    - name: Manage Logical Volume Management
      ansible.builtin.include_role:
        name: clusterlust.openebs
        tasks_from: lvm

    - name: Manage ZFS
      ansible.builtin.include_role:
        name: clusterlust.openebs
        tasks_from: zfs

    - name: Manage OpenEBS
      ansible.builtin.include_role:
        name: clusterlust.openebs
        tasks_from: preparation

- name: Manage Storage
  hosts: localhost
  become: false
  gather_facts: true
  vars:
    # Semaphore does not pass $HOME so K8S_AUTH_KUBECONFIG needs to be set.
    k8s_auth_kubeconfig: /home/semaphore/.kube/config
  tasks:
    - name: Manage OpenEBS
      ansible.builtin.include_role:
        name: clusterlust.openebs
        tasks_from: installation
