#!/usr/bin/env ansible-playbook
---
- name: Common
  hosts: all:!localhost:!jumphost
  become: true
  gather_facts: false
  pre_tasks:
    - name: Set hostname
      ansible.builtin.hostname:
        name: "{{ inventory_hostname }}"

#   - name: Clone the collection
#     delegate_to: localhost
#     connection: local
#     become: false
#     ansible.builtin.git:
#       repo: https://github.com/kubernetes-sigs/kubespray.git
#       version: v2.26.0
#       dest: "/usr/share/ansible/collections/ansible_collection/kubernetes_sigs/kubespray"

- name: Install Kubernetes
  become: true
  ansible.builtin.import_playbook: kubernetes_sigs.kubespray.cluster
  tags: kubernetes
