---
# tasks file for bbaassssiiee.openebs
- name: Ensure host path directory exists
  ansible.builtin.file:
    path: "{{ base_path }}"
    state: directory

- name: Ensure mount directory exists
  ansible.builtin.file:
    path: "{{ mount_path }}"
    state: directory

- name: Setup helm repository
  kubernetes.core.helm_repository:
    name: "{{ helm_repo_name }}"
    url: "{{ helm_repo_url }}"
    state: present

- name: Install the OpenEBS  helm chart
  kubernetes.core.helm:
    name: "{{ helm_chart_name }}"
    chart_ref: "{{ helm_repo_name }}/{{ helm_chart_name }}"
    update_repo_cache: true
    release_namespace: "{{ ebs_namespace }}"
    create_namespace: true
    state: present
    values:
      engines.replicated.mayastor.enabled: "{{ engines.replicated.mayastor.enabled }}"
      engines.local.zfs.enabled: "{{ engines.local.zfs.enabled }}"
      engines.local.lvm.enabled: "{{ engines.local.lvm.enabled }}"
