# kbcli
desired_state: present
verify_state: true
use_kbcli: true
kbcli_download_package: true

kbcli_releases_url: 'https://api.github.com/repos/apecloud/kbcli/releases/latest'
kbcli_repo_url: 'https://github.com/apecloud/kbcli/releases/download'
kbcli_path: /usr/local/bin
