# Verify desired state, both absent and present can be verified.
---
- name: "State variable - {{ desired_state }}"
  ansible.builtin.include_vars: "{{ desired_state }}.yml"

- name: "Plan: {{ package_clause }}"
  ansible.builtin.assert:
    that: package_clause is defined

- name: Gather package facts
  ansible.builtin.package_facts:
  no_log: true

- name: "Test: {{ package_clause }}"
  ansible.builtin.assert:
    quiet: true
    that:
      - package_clause
